header:
  version: 14
machine: generic
local_conf_header:
  default: | 
    INHERIT += "extrausers"
    # user setup
    EXTRA_USERS_PARAMS = "usermod -p '' root;"
    # overlayfs
    OVERLAYFS_MOUNT_POINT[data] = "/var/lib/containers/storage/overlay"
    OVERLAYFS_WRITABLE_PATHS[data] = "/var/lib/containers/storage/overlay"
    # distro config 
    DISTRO_FEATURES:append = " overlayfs systemd virtualization usrmerge acl xattr pam"
    # DISTRO_FEATURES_NATIVE:append = " overlayfs systemd"
    # DISTRO_FEATURES_NATIVESDK:append = " overlayfs systemd"
    VIRTUAL-RUNTIME_init_manager = "systemd"
    VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
    IMAGE_INSTALL:append = " podman bluechi"
    GOVERSION = "1.20.10"
    PV:pn-go = "1.20.10"
    PV:pn-go-binary-native = "1.20.10"
    PV:pn-go-cross = "1.20.10"
    PV:pn-go-cross-canadian = "1.20.10"
    PV:pn-go-crosssdk = "1.20.10"
    PV:pn-go-native = "1.20.10"
    PV:pn-go-runtime = "1.20.10"
    
    PV:pn-podman = "4.8.3"
repos:
  poky: 
    url: https://git.yoctoproject.org/git/poky
    branch: kirkstone
    path: layers/poky
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
    patches:
      p1:
        repo : poky
        path : ../../patches/0001-enable-go-1.20.10.patch
  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: kirkstone
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-filesystems:
      meta-python:
      meta-networking: 
  meta-virtualization:
    url: git://git.yoctoproject.org/meta-virtualization
    branch: kirkstone
    path: layers/meta-virtualization
    patches:
      p1:
        repo: meta-virtualization
        path: ../../patches/0001-enable-podman-4.8.3.patch
  meta-bluechi:
    # url: https://github.com/eclipse-bluechi/bluechi-on-yocto.git
    # branch: main
    path: ../
    layers:
      meta-bluechi:
